spring:
  application:
    name: Mini-doodle
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/doodle}
    username: ${SPRING_DATASOURCE_USERNAME:doodle}
    password: ${SPRING_DATASOURCE_PASSWORD:doodle}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true
    baseline-on-migrate: true

server:
  port: ${SERVER_PORT:8080}
